/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppPanListRouteImport } from './routes/app.pan-list'
import { Route as AppPanFinderRouteImport } from './routes/app.pan-finder'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiPaymentVerifyRouteImport } from './routes/api/payment-verify'
import { Route as ApiPaymentCreateRouteImport } from './routes/api/payment-create'
import { Route as ApiPanFindRouteImport } from './routes/api/pan-find'
import { Route as AppWalletPaymentReturnRouteImport } from './routes/app.wallet.payment-return'
import { Route as ApiPublicPaymentCallbackRouteImport } from './routes/api/public/payment-callback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppPanListRoute = AppPanListRouteImport.update({
  id: '/pan-list',
  path: '/pan-list',
  getParentRoute: () => AppRoute,
} as any)
const AppPanFinderRoute = AppPanFinderRouteImport.update({
  id: '/pan-finder',
  path: '/pan-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPaymentVerifyRoute = ApiPaymentVerifyRouteImport.update({
  id: '/api/payment-verify',
  path: '/api/payment-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment-create',
  path: '/api/payment-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanFindRoute = ApiPanFindRouteImport.update({
  id: '/api/pan-find',
  path: '/api/pan-find',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletPaymentReturnRoute = AppWalletPaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => AppWalletRoute,
} as any)
const ApiPublicPaymentCallbackRoute =
  ApiPublicPaymentCallbackRouteImport.update({
    id: '/api/public/payment-callback',
    path: '/api/public/payment-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/pan-find': typeof ApiPanFindRoute
  '/api/payment-create': typeof ApiPaymentCreateRoute
  '/api/payment-verify': typeof ApiPaymentVerifyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/pan-finder': typeof AppPanFinderRoute
  '/app/pan-list': typeof AppPanListRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/app/wallet/payment-return': typeof AppWalletPaymentReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/pan-find': typeof ApiPanFindRoute
  '/api/payment-create': typeof ApiPaymentCreateRoute
  '/api/payment-verify': typeof ApiPaymentVerifyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/pan-finder': typeof AppPanFinderRoute
  '/app/pan-list': typeof AppPanListRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/app/wallet/payment-return': typeof AppWalletPaymentReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/pan-find': typeof ApiPanFindRoute
  '/api/payment-create': typeof ApiPaymentCreateRoute
  '/api/payment-verify': typeof ApiPaymentVerifyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/pan-finder': typeof AppPanFinderRoute
  '/app/pan-list': typeof AppPanListRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/payment-callback': typeof ApiPublicPaymentCallbackRoute
  '/app/wallet/payment-return': typeof AppWalletPaymentReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/pan-find'
    | '/api/payment-create'
    | '/api/payment-verify'
    | '/app/admin'
    | '/app/pan-finder'
    | '/app/pan-list'
    | '/app/support'
    | '/app/wallet'
    | '/app/'
    | '/api/public/payment-callback'
    | '/app/wallet/payment-return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/pan-find'
    | '/api/payment-create'
    | '/api/payment-verify'
    | '/app/admin'
    | '/app/pan-finder'
    | '/app/pan-list'
    | '/app/support'
    | '/app/wallet'
    | '/app'
    | '/api/public/payment-callback'
    | '/app/wallet/payment-return'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/pan-find'
    | '/api/payment-create'
    | '/api/payment-verify'
    | '/app/admin'
    | '/app/pan-finder'
    | '/app/pan-list'
    | '/app/support'
    | '/app/wallet'
    | '/app/'
    | '/api/public/payment-callback'
    | '/app/wallet/payment-return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPanFindRoute: typeof ApiPanFindRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  ApiPaymentVerifyRoute: typeof ApiPaymentVerifyRoute
  ApiPublicPaymentCallbackRoute: typeof ApiPublicPaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pan-list': {
      id: '/app/pan-list'
      path: '/pan-list'
      fullPath: '/app/pan-list'
      preLoaderRoute: typeof AppPanListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pan-finder': {
      id: '/app/pan-finder'
      path: '/pan-finder'
      fullPath: '/app/pan-finder'
      preLoaderRoute: typeof AppPanFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/payment-verify': {
      id: '/api/payment-verify'
      path: '/api/payment-verify'
      fullPath: '/api/payment-verify'
      preLoaderRoute: typeof ApiPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-create': {
      id: '/api/payment-create'
      path: '/api/payment-create'
      fullPath: '/api/payment-create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pan-find': {
      id: '/api/pan-find'
      path: '/api/pan-find'
      fullPath: '/api/pan-find'
      preLoaderRoute: typeof ApiPanFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet/payment-return': {
      id: '/app/wallet/payment-return'
      path: '/payment-return'
      fullPath: '/app/wallet/payment-return'
      preLoaderRoute: typeof AppWalletPaymentReturnRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/api/public/payment-callback': {
      id: '/api/public/payment-callback'
      path: '/api/public/payment-callback'
      fullPath: '/api/public/payment-callback'
      preLoaderRoute: typeof ApiPublicPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppWalletRouteChildren {
  AppWalletPaymentReturnRoute: typeof AppWalletPaymentReturnRoute
}

const AppWalletRouteChildren: AppWalletRouteChildren = {
  AppWalletPaymentReturnRoute: AppWalletPaymentReturnRoute,
}

const AppWalletRouteWithChildren = AppWalletRoute._addFileChildren(
  AppWalletRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppPanFinderRoute: typeof AppPanFinderRoute
  AppPanListRoute: typeof AppPanListRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWalletRoute: typeof AppWalletRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppPanFinderRoute: AppPanFinderRoute,
  AppPanListRoute: AppPanListRoute,
  AppSupportRoute: AppSupportRoute,
  AppWalletRoute: AppWalletRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPanFindRoute: ApiPanFindRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  ApiPaymentVerifyRoute: ApiPaymentVerifyRoute,
  ApiPublicPaymentCallbackRoute: ApiPublicPaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
